# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cabea39f5f006446485ae759054c736a938ffbf415f7ad94142f82dbf8249063923afe36f6c8f5b20c51cb830cd23370e58800abd256a9db845cf478947af5d

test:
  secret_key_base: e18a7fc8156d6b9c326b5a00d8bcf13dad38145f635dbc62dcdc605ed8dab881b6be74127db5588c4581ff145d76a44697916091932264e39d0dc98c6513f29b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
